name: Build Latest

on: [workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '8.0.*'

jobs:

  build-linux-arm64:
    
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm64-20220312201346-b2c2436
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: dotnet publish BBDown -r linux-arm64 -c Release -p:CppCompilerAndLinker=clang-9 -p:SysRoot=/crossrootfs/arm64 -o artifact
      
      - name: Upload Artifact[linux-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_linux-arm64
          path: artifact/BBDown
          
  build-mac-x64-arm64:
    
    runs-on: macOS-latest
    
    steps:
      
      - uses: actions/checkout@v2
      
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: dotnet publish BBDown -r osx-arm64 -c Release -o artifact-arm64 
      - run: dotnet publish BBDown -r osx-x64 -c Release -o artifact-x64 

      
      - name: Upload Artifact[osx-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_osx-x64
          path: artifact-x64/BBDown
          
      - name: Upload Artifact[osx-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_osx-arm64
          path: artifact-arm64/BBDown
